spring.application.name=Chat-OSS
server.port=8089
spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848

minio.endpoint=http://localhost:9000
minio.access-key=admin
minio.secret-key=Admin@123456
minio.bucket-name=chat-image
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Nacos ??????
spring.cloud.nacos.config.server-addr=127.0.0.1:8848

# ?? Nacos ??????
# ?? optional: ??????????????
# ?????????
spring.config.import=optional:nacos:${spring.application.name}.properties,optional:nacos:global-config.properties