spring.application.name=Chat-Gateway
server.port=8081
spring.cloud.gateway.routes[0].id=Chat-User
spring.cloud.gateway.routes[0].uri=lb://Chat-User
spring.cloud.gateway.routes[0].predicates[0]=Path=/user/**

spring.cloud.gateway.routes[1].id=Chat-Content
spring.cloud.gateway.routes[1].uri=lb://Chat-Content
spring.cloud.gateway.routes[1].predicates[0]=Path=/content/**

spring.cloud.gateway.routes[2].id=Chat-Log
spring.cloud.gateway.routes[2].uri=lb://Chat-Log
spring.cloud.gateway.routes[2].predicates[0]=Path=/log/**

spring.cloud.gateway.routes[3].id=Chat-RiskControl
spring.cloud.gateway.routes[3].uri=lb://Chat-RiskControl
spring.cloud.gateway.routes[3].predicates[0]=Path=/risk/**

spring.cloud.gateway.routes[4].id=Chat-Manage
spring.cloud.gateway.routes[4].uri=lb://Chat-Manage
spring.cloud.gateway.routes[4].predicates[0]=Path=/manage/**

spring.cloud.gateway.routes[5].id=Chat-OSS
spring.cloud.gateway.routes[5].uri=lb://Chat-OSS
spring.cloud.gateway.routes[5].predicates[0]=Path=/oss/**

# Nacos ??????
spring.cloud.nacos.config.server-addr=127.0.0.1:8848

# ?? Nacos ??????
# ?? optional: ??????????????
# ?????????
spring.config.import=optional:nacos:${spring.application.name}.properties,optional:nacos:global-config.properties